version: "3.9"

services:
  server:
    build: ./server
    ports:
      - 8080:8080
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - 8081:8081
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
