 name: Build and run C++ app

    on:
     push:
      branches: [ master ]
     pull_request:
      branches: [ master ]

    jobs:
     docker:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build and run Docker container
        run: |
         docker-compose up --build -d
